[[axis]]
id = "econ"
name = "Economic"
weights = [10, 15, 20, 10, 20, 15, 10]
tiers = [
	"Communist",
	"Socialist",
	"Social",
	"Centrist",
	"Market",
	"Capitalist",
	"Laissez-Faire",
]

[axis.left]
name = "Equality"
color = "#d32f2f"
description = "Those with higher Equality scores believe the economy should distribute value evenly among the populace. They tend to support progressive tax codes, social programs, and at high values, socialism."

[axis.right]
name = "Markets"
color = "#00796b"
description = "Those with higher Market scores believe the economy should be focused on rapid growth. They tend to support lower taxes, privatization, deregulation, and at high values, laissez-faire capitalism."

[[axis]]
id = "dipl"
name = "Diplomatic"
tiers = [
	"Cosmopolitan",
	"Internationalist",
	"Peaceful",
	"Balanced",
	"Patriotic",
	"Nationalist",
	"Chauvinist",
]

[axis.left]
name = "Globe"
color = "#0288d1"
description = "Those with higher Globe scores are cosmopolitan and globalist. They often believe in a peaceful foreign policy, emphasizing diplomacy, cooperation, integration, and at high values, a world government."

[axis.right]
name = "Nation"
color = "#f57c00"
description = "Those with higher Nation scores are patriotic and nationalist. They often believe in an aggressive foreign policy, valuing the military, strength, sovereignty, and at high values, territorial expansion."

[[axis]]
id = "govt"
name = "Civil"
tiers = [
	"Anarchist",
	"Libertarian",
	"Liberal",
	"Moderate",
	"Statist",
	"Authoritarian",
	"Totalitarian",
]

[axis.left]
name = "Liberty"
color = "#fbc02d"
description = "Those with higher Liberty scores believe in strong civil liberties. They tend to support democracy and oppose state intervention in personal lives. Note that this refers to civil liberties, not economic liberties."

[axis.right]
name = "Authority"
color = "#303f9f"
description = "Those with higher Authority scores believe in strong state power. They tend to support state intervention in personal lives, government surveillance, and at high values, censorship or autocracy."

[[axis]]
id = "scty"
name = "Society"
tiers = [
	"Revolutionary",
	"Very Progressive",
	"Progressive",
	"Neutral",
	"Traditional",
	"Very Traditional",
	"Reactionary",
]

[axis.left]
name = "Progress"
color = "#7b1fa2"
description = "Those with higher Progress scores believe in social change and rationality. Though not always, they are usually secular or atheist, and support environmental action and scientific or technological research."

[axis.right]
name = "Tradition"
color = "#689f38"
description = "Those with higher Tradition scores believe in traditional values and strict adherence to a moral code. Though not always, they are usually religious, and support the status quo or the status quo ante."
