[[questions]]
question = "Oppression by corporations is more of a concern than oppression by governments."
[questions.effect]
econ = 10
dipl = 0
govt = -5
scty = 0
[[questions]]
question = "It is necessary for the government to intervene in the economy to protect consumers."
[questions.effect]
econ = 10
dipl = 0
govt = 0
scty = 0
[[questions]]
question = "The freer the markets the freer the people."
[questions.effect]
econ = -10
dipl = 0
govt = 0
scty = 0
[[questions]]
question = "It is better to maintain a balanced budget than to ensure welfare for all citizens."
[questions.effect]
econ = -10
dipl = 0
govt = 0
scty = 0
[[questions]]
question = "Publicly-funded research is more beneficial to the people than leaving it to the market."
[questions.effect]
econ = 10
dipl = 0
govt = 0
scty = 10
[[questions]]
question = "Tariffs on international trade are important to encourage local production."
[questions.effect]
econ = 5
dipl = 0
govt = -10
scty = 0
[[questions]]
question = "From each according to his ability to each according to his needs."
[questions.effect]
econ = 10
dipl = 0
govt = 0
scty = 0
[[questions]]
question = "It would be best if social programs were abolished in favor of private charity."
[questions.effect]
econ = -10
dipl = 0
govt = 0
scty = 0
[[questions]]
question = "Taxes should be increased on the rich to provide for the poor."
[questions.effect]
econ = 10
dipl = 0
govt = 0
scty = 0
[[questions]]
question = "Inheritance is a legitimate form of wealth."
[questions.effect]
econ = -10
dipl = 0
govt = 0
scty = -5
[[questions]]
question = "Basic utilities like roads and electricity should be publicly owned."
[questions.effect]
econ = 10
dipl = 0
govt = 0
scty = 0
[[questions]]
question = "Government intervention is a threat to the economy."
[questions.effect]
econ = -10
dipl = 0
govt = 0
scty = 0
[[questions]]
question = "Those with a greater ability to pay should receive better healthcare."
[questions.effect]
econ = -10
dipl = 0
govt = 0
scty = 0
[[questions]]
question = "Quality education is a right of all people."
[questions.effect]
econ = 10
dipl = 0
govt = 0
scty = 5
[[questions]]
question = "The means of production should belong to the workers who use them."
[questions.effect]
econ = 10
dipl = 0
govt = 0
scty = 0
[[questions]]
question = "The United Nations should be abolished."
[questions.effect]
econ = 0
dipl = -10
govt = -5
scty = 0
[[questions]]
question = "Military action by our nation is often necessary to protect it."
[questions.effect]
econ = 0
dipl = -10
govt = -10
scty = 0
[[questions]]
question = "I support regional unions such as the European Union."
[questions.effect]
econ = -5
dipl = 10
govt = 10
scty = 5
[[questions]]
question = "It is important to maintain our national sovereignty."
[questions.effect]
econ = 0
dipl = -10
govt = -5
scty = 0
[[questions]]
question = "A united world government would be beneficial to mankind."
[questions.effect]
econ = 0
dipl = 10
govt = 0
scty = 0
[[questions]]
question = "It is more important to retain peaceful relations than to further our strength."
[questions.effect]
econ = 0
dipl = 10
govt = 0
scty = 0
[[questions]]
question = "Wars do not need to be justified to other countries."
[questions.effect]
econ = 0
dipl = -10
govt = -10
scty = 0
[[questions]]
question = "Military spending is a waste of money."
[questions.effect]
econ = 0
dipl = 10
govt = 10
scty = 0
[[questions]]
question = "International aid is a waste of money."
[questions.effect]
econ = -5
dipl = -10
govt = 0
scty = 0
[[questions]]
question = "My nation is great."
[questions.effect]
econ = 0
dipl = -10
govt = 0
scty = 0
[[questions]]
question = "Research should be conducted on an international scale."
[questions.effect]
econ = 0
dipl = 10
govt = 0
scty = 10
[[questions]]
question = "Governments should be accountable to the international community."
[questions.effect]
econ = 0
dipl = 10
govt = 5
scty = 0
[[questions]]
question = "Even when protesting an authoritarian government violence is not acceptable."
[questions.effect]
econ = 0
dipl = 5
govt = -5
scty = 0
[[questions]]
question = "My religious values should be spread as much as possible."
[questions.effect]
econ = 0
dipl = -5
govt = -10
scty = -10
[[questions]]
question = "Our nation's values should be spread as much as possible."
[questions.effect]
econ = 0
dipl = -10
govt = -5
scty = 0
[[questions]]
question = "It is very important to maintain law and order."
[questions.effect]
econ = 0
dipl = -5
govt = -10
scty = -5
[[questions]]
question = "The general populace makes poor decisions."
[questions.effect]
econ = 0
dipl = 0
govt = -10
scty = 0
[[questions]]
question = "Physician-assisted suicide should be legal."
[questions.effect]
econ = 0
dipl = 0
govt = 10
scty = 0
[[questions]]
question = "The sacrifice of some civil liberties is necessary to protect us from acts of terrorism."
[questions.effect]
econ = 0
dipl = 0
govt = -10
scty = 0
[[questions]]
question = "Government surveillance is necessary in the modern world."
[questions.effect]
econ = 0
dipl = 0
govt = -10
scty = 0
[[questions]]
question = "The very existence of the state is a threat to our liberty."
[questions.effect]
econ = 0
dipl = 0
govt = 10
scty = 0
[[questions]]
question = "Regardless of political opinions it is important to side with your country."
[questions.effect]
econ = 0
dipl = -10
govt = -10
scty = -5
[[questions]]
question = "All authority should be questioned."
[questions.effect]
econ = 0
dipl = 0
govt = 10
scty = 5
[[questions]]
question = "A hierarchical state is best."
[questions.effect]
econ = 0
dipl = 0
govt = -10
scty = 0
[[questions]]
question = "It is important that the government follows the majority opinion even if it is wrong."
[questions.effect]
econ = 0
dipl = 0
govt = 10
scty = 0
[[questions]]
question = "The stronger the leadership the better."
[questions.effect]
econ = 0
dipl = -10
govt = -10
scty = 0
[[questions]]
question = "Democracy is more than a decision-making process."
[questions.effect]
econ = 0
dipl = 0
govt = 10
scty = 0
[[questions]]
question = "Environmental regulations are essential."
[questions.effect]
econ = 5
dipl = 0
govt = 0
scty = 10
[[questions]]
question = "A better world will come from automation science and technology."
[questions.effect]
econ = 0
dipl = 0
govt = 0
scty = 10
[[questions]]
question = "Children should be educated in religious or traditional values."
[questions.effect]
econ = 0
dipl = 0
govt = -5
scty = -10
[[questions]]
question = "Traditions are of no value on their own."
[questions.effect]
econ = 0
dipl = 0
govt = 0
scty = 10
[[questions]]
question = "Religion should play a role in government."
[questions.effect]
econ = 0
dipl = 0
govt = -10
scty = -10
[[questions]]
question = "Churches should be taxed the same way other institutions are taxed."
[questions.effect]
econ = 5
dipl = 0
govt = 0
scty = 10
[[questions]]
question = "Climate change is currently one of the greatest threats to our way of life."
[questions.effect]
econ = 0
dipl = 0
govt = 0
scty = 10
[[questions]]
question = "It is important that we work as a united world to combat climate change."
[questions.effect]
econ = 0
dipl = 10
govt = 0
scty = 10
[[questions]]
question = "Society was better many years ago than it is now."
[questions.effect]
econ = 0
dipl = 0
govt = 0
scty = -10
[[questions]]
question = "It is important that we maintain the traditions of our past."
[questions.effect]
econ = 0
dipl = 0
govt = 0
scty = -10
[[questions]]
question = "It is important that we think in the long term beyond our lifespans."
[questions.effect]
econ = 0
dipl = 0
govt = 0
scty = 10
[[questions]]
question = "Reason is more important than maintaining our culture."
[questions.effect]
econ = 0
dipl = 0
govt = 0
scty = 10
[[questions]]
question = "Drug use should be legalized or decriminalized."
[questions.effect]
econ = 0
dipl = 0
govt = 10
scty = 2
[[questions]]
question = "Same-sex marriage should be legal."
[questions.effect]
econ = 0
dipl = 0
govt = 10
scty = 10
[[questions]]
question = "No cultures are superior to others."
[questions.effect]
econ = 0
dipl = 10
govt = 5
scty = 10
[[questions]]
question = "Sex outside marriage is immoral."
[questions.effect]
econ = 0
dipl = 0
govt = -5
scty = -10
[[questions]]
question = "If we accept migrants at all it is important that they assimilate into our culture."
[questions.effect]
econ = 0
dipl = 0
govt = -5
scty = -10
[[questions]]
question = "Abortion should be prohibited in most or all cases."
[questions.effect]
econ = 0
dipl = 0
govt = -10
scty = -10
[[questions]]
question = "Gun ownership should be prohibited for those without a valid reason."
[questions.effect]
econ = 0
dipl = 0
govt = -10
scty = 0
[[questions]]
question = "I support single-payer universal healthcare."
[questions.effect]
econ = 10
dipl = 0
govt = 0
scty = 0
[[questions]]
question = "Prostitution should be illegal."
[questions.effect]
econ = 0
dipl = 0
govt = -10
scty = -10
[[questions]]
question = "Maintaining family values is essential."
[questions.effect]
econ = 0
dipl = 0
govt = 0
scty = -10
[[questions]]
question = "To chase progress at all costs is dangerous."
[questions.effect]
econ = 0
dipl = 0
govt = 0
scty = -10
[[questions]]
question = "Genetic modification is a force for good even on humans."
[questions.effect]
econ = 0
dipl = 0
govt = 0
scty = 10
[[questions]]
question = "We should open our borders to immigration."
[questions.effect]
econ = 0
dipl = 10
govt = 10
scty = 0
[[questions]]
question = "Governments should be as concerned about foreigners as they are about their own citizens."
[questions.effect]
econ = 0
dipl = 10
govt = 0
scty = 0
[[questions]]
question = "All people - regardless of factors like culture or sexuality - should be treated equally."
[questions.effect]
econ = 10
dipl = 10
govt = 10
scty = 10
[[questions]]
question = "It is important that we further my group's goals above all others."
[questions.effect]
econ = -10
dipl = -10
govt = -10
scty = -10
